#-------------------------------
# General Site Settings
title: Max Du
description: "Senior Data Analyst | Expert in Data Management, Power BI, Python, SQL, ETL, and Machine Learning | Skilled in Business Intelligence, Data Visualization, and Collaborative Decision-Making"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Senior Data Analyst <span style="color:#f58506"> Portfolio </span>
location: "TAS, Australia"
avatar_image: /img/profile_picture.JPG

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/max-du-55a7b9204/" # Add your linkedln handle
github: "https://github.com/iMaxdu"  # Add your github handle

#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

